# Generated by Django 4.0.3 on 2022-04-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectifyapp', '0002_dedication_dedicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dedication',
            name='dedicacion',
        ),
        migrations.AddField(
            model_name='dedication',
            name='dedication',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
